name: Publish to NPM
on:
  workflow_call:
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "25"
          registry-url: "https://registry.npmjs.org"
      - name: "Publish to NPM"
        run: |
          npm install
          npm run build
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DATA_TRAILS_NPM_TOKEN }}
